In [1]:
import numpy as np
np.__version__

'2.4.0'

In [5]:
arr1 = np.array([1, 3, 5, 7, 9])
print(arr1)
arr2 = np.array([1, 3, 5, 7, 9])
print(arr2)
print(type(arr1))
print(id(arr1))

[1 3 5 7 9]
[1 3 5 7 9]
<class 'numpy.ndarray'>
1915564629456


In [6]:
# Shallow copy - both arr3 and arr1 point to the same object
arr3 = arr1
print(id(arr3))
print(id(arr1))

1915564629456
1915564629456


In [ ]:
# Deep copy - arr4 is a new object
arr4 = arr1.copy()
print(id(arr4))
print(id(arr1))

2009388610832
2009388602960


In [7]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(10, 20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [9]:
np.arange(10, 20, 3)

array([10, 13, 16, 19])

In [7]:
len(arr1)

5

In [8]:
arr1.size

5

In [19]:
arr = np.linspace(0, 10, 5) # (end - start) / size - 1
print(arr)
a = np.linspace(0, 10, 3, retstep=True)
print(a)

[ 0.   2.5  5.   7.5 10. ]
(array([ 0.,  5., 10.]), np.float64(5.0))


In [20]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [21]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [27]:
np.zeros(5, dtype=int)

array([0, 0, 0, 0, 0])

In [28]:
np.zeros(5, dtype = int).dtype

dtype('int64')

In [29]:
x = np.zeros(5, dtype = int)
print(x)
print(type(x[0]))
print(type(x))

[0 0 0 0 0]
<class 'numpy.int64'>
<class 'numpy.ndarray'>


In [31]:
arr = np.ones((2, 3), dtype = int)
print(arr)
arr.dtype

[[1 1 1]
 [1 1 1]]


dtype('int64')

In [ ]:
print(np.dtype(np.int_).itemsize)
print(np.dtype(np.int64).itemsize)
# Output - 8 bytes = 64 bit

8
8


In [34]:
arr.astype(float)

array([[1., 1., 1.],
       [1., 1., 1.]])

In [36]:
arr1 = np.array([111, 2.3, True, False, False], dtype = int)
print(arr1)

[111   2   1   0   0]


In [ ]:
arr2 = np.array([111, 2.3, 'python', 'abc'])
print(arr2) # Converts everything to string

['111' '2.3' 'python' 'abc']
<class 'numpy.ndarray'>


In [ ]:
arr3 = [111, 2.3, 'python', 'abc']
print(arr3) # Retains original data types

[111, 2.3, 'python', 'abc']


In [40]:
a = np.array([1, 2, 3, 4, 5])
a[2]

np.int64(3)

In [41]:
a[-3]

np.int64(3)

In [42]:
a[:]

array([1, 2, 3, 4, 5])

In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
a.size # Total number of elements

9

In [45]:
a[1]

array([4, 5, 6])

In [46]:
a[-1]

array([7, 8, 9])

In [47]:
a[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [48]:
a[2][1]

np.int64(8)

In [50]:
a[2, 1]

np.int64(8)

In [ ]:
a[[0, 2]]
# It displays 0th and 2nd rows

array([[1, 2, 3],
       [7, 8, 9]])

In [ ]:
a[1:, 1:]
# It displays all rows from 1st row and all columns from 1st column

array([[5, 6],
       [8, 9]])

In [61]:
arr = np.arange(100)
arrMask = arr % 5 == 0
print(arr[arrMask])

[ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


In [66]:
arr = np.arange(100)
arrMask = (arr % 5 == 0) & (arr > 0)
arr[arrMask]

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85,
       90, 95])

In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a.size) # Number of columns
print(a.shape) # Number of rows
print(a.ndim) # Number of dimensions - 2 x 2

9
(3, 3)
2


In [74]:
a = np.arange(15)
print(a)
print(id(a))
a = a.reshape(3, 5)
print(a)
print(id(a))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
1915566727760
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
1915566723248


In [ ]:
a = np.arange(10) # Shallow copy
print(a)
b = a.reshape(2, 5)
print(b)
a[0] = 999
print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[999   1   2   3   4   5   6   7   8   9]
[[999   1   2   3   4]
 [  5   6   7   8   9]]


In [ ]:
c = a.reshape(2, 5).copy() # Deep copy
c[0, 0] = 0
print(a)
print(c)

[999   1   2   3   4   5   6   7   8   9]
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [84]:
a = np.array([[1, 2], [3, 4]])
b = np.append(a, [[9, 9]], axis = 0)
print(b)

[[1 2]
 [3 4]
 [9 9]]


In [86]:
c = np.append(a, [[5], [9]], axis = 1)
print(c)

[[1 2 5]
 [3 4 9]]


In [89]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)
a = np.delete(a, 0)
print(a)

[[1 2 3]
 [4 5 6]]
[2 3 4 5 6]


In [90]:
np.delete(a, (0, 2, 4))

array([3, 5])

In [92]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)
a = np.delete(a, 0, axis = 0)
print(a)

[[1 2 3]
 [4 5 6]]
[[4 5 6]]


In [94]:
a = [1, 2, 3]
print(a + a)
print(a*3)

[1, 2, 3, 1, 2, 3]
[1, 2, 3, 1, 2, 3, 1, 2, 3]


In [96]:
b = np.array([1, 2, 3])
print(b + b)
print(b*3)

[2 4 6]
[3 6 9]


In [ ]:
np.repeat(b, 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
a + b # Matrix Addition

array([5, 7, 9])

In [99]:
1.0*a/b

array([0.25, 0.4 , 0.5 ])

In [5]:
x = np.array(6)
print(x)
np.sqrt(x)
np.exp(x)

6


np.float64(403.4287934927351)

In [ ]:
a = 10
print(type(np.sqrt)) # Belongs to universal function

<class 'numpy.ufunc'>


In [2]:
np.random.seed(6)
a = np.random.randint(1, 11, size = 50)
print(a)

[10  4  5  1 10  2 10  2  5  2  9  3  5  3  6 10  7  3  6  6  2  5  6  1
  3  3  4  6 10  6  3  8  9  6  7  4  6  2  3  4  7 10 10  9  1  4  8  5
  9  2]


In [20]:
b = np.unique(a)
print(b)

[ 1  2  3  4  5  6  7  8  9 10]


In [21]:
c = np.median(b)
print(c)

5.5


In [22]:
d = np.median(a)
print(d)

5.0


In [23]:
np.sum(a)

np.int64(272)

In [24]:
np.round(np.var(a), 2)

np.float64(8.05)

In [25]:
np.round(np.std(a), 2)

np.float64(2.84)

In [26]:
np.max(a)

np.int32(10)

In [27]:
np.min(a)

np.int32(1)

In [ ]:
x = np.arange(1, 11)
print(x)
print(x.sum())
print(x.mean())
print(np.median(x))
print(x.std())
print(x.cumsum())

[ 1  2  3  4  5  6  7  8  9 10]
55
5.5
5.5
2.8722813232690143
[ 1  3  6 10 15 21 28 36 45 55]


In [38]:
y = np.arange(1, 10)
print(y)
y = y.reshape(3, 3)
print(y)
y = y.reshape(-1, 3)
print(y)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [43]:
print(y.mean(axis = 0, dtype = int))

[4 5 6]


In [44]:
print(y.mean(axis = 1, dtype = int))

[2 5 8]


In [46]:
np.random.seed(10)
z = np.random.randint(10, size = 1000)
print(z)

[9 4 0 1 9 0 1 8 9 0 8 6 4 3 0 4 6 8 1 8 4 1 3 6 5 3 9 6 9 1 9 4 2 6 7 8 8
 9 2 0 6 7 8 1 7 1 4 0 8 5 4 7 8 8 2 6 2 8 8 6 6 5 6 0 0 6 9 1 8 9 1 2 8 9
 9 5 0 2 7 3 0 4 2 0 3 3 1 2 5 9 0 1 0 1 9 0 9 2 1 1 0 0 5 9 0 4 6 6 0 2 3
 3 2 6 0 5 1 3 6 5 5 1 8 0 5 9 8 5 7 8 5 8 9 9 1 5 9 1 4 7 7 7 9 7 6 0 3 9
 4 4 6 8 4 9 2 1 1 6 3 4 5 4 0 2 8 0 7 6 5 8 2 2 0 1 2 3 5 7 8 7 7 6 9 2 0
 4 5 4 6 9 0 4 6 4 9 8 0 7 1 7 1 1 5 5 0 8 3 7 1 5 2 3 4 5 7 6 8 0 4 6 3 5
 9 3 8 3 0 9 6 2 3 9 1 4 0 5 0 8 1 3 6 0 0 6 5 7 4 9 0 0 9 2 2 1 6 6 7 3 9
 0 7 7 9 0 2 2 0 5 8 0 5 9 3 9 6 9 7 8 0 9 6 0 1 0 1 9 4 9 0 1 7 9 3 0 8 1
 5 4 5 4 3 4 4 1 1 2 1 1 2 2 2 5 8 1 7 1 7 1 8 0 6 7 5 1 2 6 1 5 8 0 3 9 6
 3 0 2 8 9 8 0 7 7 4 6 3 4 5 3 5 9 2 3 2 2 5 8 4 1 6 7 1 7 1 2 9 2 7 4 6 7
 3 2 3 9 2 5 0 7 2 6 5 7 3 7 0 3 6 0 7 2 9 5 1 0 2 3 1 4 2 0 2 8 8 8 6 5 8
 8 8 0 6 1 2 8 3 9 8 6 7 5 1 6 9 6 7 9 5 9 2 4 8 9 2 0 0 6 8 6 4 7 7 0 6 4
 9 7 1 5 1 3 6 3 1 0 7 0 3 2 7 5 1 6 5 3 7 2 3 4 6 4 2 6 8 8 9 9 4 4 7 1 7
 8 0 8 9 5 7 2 3 5 3 0 7 

In [47]:
z.max()

np.int32(9)

In [48]:
z.min()

np.int32(0)

In [50]:
(z > 5).sum()

np.int64(414)

In [51]:
np.unique(z)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

In [54]:
print(set(sorted(z)))

{np.int32(0), np.int32(1), np.int32(2), np.int32(3), np.int32(4), np.int32(5), np.int32(6), np.int32(7), np.int32(8), np.int32(9)}


In [3]:
a.argmax()

np.int64(0)